=== knzelhar/Gestion-des-notes/ELHARIRI_ELYAZGHI/src/Notes/Note.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Students (Student+)>
<!ELEMENT Student (module+)>
<!ELEMENT module (note)>
<!ELEMENT note (#PCDATA)>
<!ATTLIST Student CNE CDATA #REQUIRED>
<!ATTLIST Student Student_Name CDATA #REQUIRED>
<!ATTLIST module code CDATA #REQUIRED>

=== knzelhar/Gestion-des-notes/ELHARIRI_ELYAZGHI/XML_FILES/Notes_GINF2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE Students SYSTEM
        "C:\Users\ASUS\Downloads\ELHARIRI_ELYAZGHI\XML_FILES\Note.dtd">
<Students><Student CNE="20000047" Student_Name="AMINE AZZMAN"><module code="GINF31"><note>17</note></module></Student><Student CNE="20000046" Student_Name="AYMANE ARIB"><module code="GINF31"><note>11</note></module></Student><Student CNE="20000068" Student_Name="SILIA EL GHAZI"><module code="GINF31"><note>16</note></module></Student><Student CNE="20000049" Student_Name="AHLAM BEN IMRAN"><module code="GINF31"><note>6</note></module></Student><Student CNE="20000048" Student_Name="CHAIMAE AZZOUZ"><module code="GINF31"><note>9</note></module></Student><Student CNE="20000050" Student_Name="ABDELILAH BENCHINE"><module code="GINF31"><note>9</note></module></Student><Student CNE="20000052" Student_Name="AMINE BERKOUKT"><module code="GINF31"><note>15</note></module></Student><Student CNE="20000051" Student_Name="ANAS BENMGUIRIDA"><module code="GINF31"><note>16</note></module></Student><Student CNE="20000054" Student_Name="SAFAA BOUHNINE"><module code="GINF31"><note>6</note></module></Student><Student CNE="20000053" Student_Name="ABDELLAH BIGAGANE"><module code="GINF31"><note>18</note></module></Student><Student CNE="20000056" Student_Name="YASSER BOULERBAH"><module code="GINF31"><note>16</note></module></Student><Student CNE="20000055" Student_Name="MOHAMMED BOUKER"><module code="GINF31"><note>8</note></module></Student><Student CNE="20000058" Student_Name="MERYEME BOUSSAID"><module code="GINF31"><note>8</note></module></Student><Student CNE="20000057" Student_Name="MOHAMMED BOUNOUAR"><module code="GINF31"><note>16</note></module></Student><Student CNE="20000059" Student_Name="SOUHAIL CHAIBERRAS"><module code="GINF31"><note>6</note></module></Student><Student CNE="20000039" Student_Name="ABDELOUAHED ABBAD "><module code="GINF31"><note>11</note></module></Student><Student CNE="20000061" Student_Name="MOAD DAHBI"><module code="GINF31"><note>8</note></module></Student><Student CNE="20000060" Student_Name="HOUSSAM CHERKI"><module code="GINF31"><note>10</note></module></Student><Student CNE="20000041" Student_Name="KENZA ABOU-EL KASEM"><module code="GINF31"><note>10</note></module></Student><Student CNE="20000063" Student_Name="EL MEHDI EL ADNANI"><module code="GINF31"><note>6</note></module></Student><Student CNE="20000040" Student_Name="SOUFIANE ABDELOUAHAB"><module code="GINF31"><note>14</note></module></Student><Student CNE="20000062" Student_Name="IMAD ECHCHRIKI"><module code="GINF31"><note>11</note></module></Student><Student CNE="20000043" Student_Name="IBTISSAM AIDOUN"><module code="GINF31"><note>14</note></module></Student><Student CNE="20000065" Student_Name="OUAAIL EL AOUAD"><module code="GINF31"><note>7</note></module></Student><Student CNE="20000042" Student_Name="AYA AHMYTTOU"><module code="GINF31"><note>15</note></module></Student><Student CNE="20000064" Student_Name="ACHRAF EL AIDI IDRISSI"><module code="GINF31"><note>11</note></module></Student><Student CNE="20000045" Student_Name="ELARBI ALLAM"><module code="GINF31"><note>17</note></module></Student><Student CNE="20000067" Student_Name="YASSINE EL GARTI"><module code="GINF31"><note>16</note></module></Student><Student CNE="20000044" Student_Name="TAREK AL AZAMI"><module code="GINF31"><note>17</note></module></Student><Student CNE="20000066" Student_Name="MALAK EL BAKALI"><module code="GINF31"><note>8</note></module></Student></Students>
